CC = gcc
CFLAGS = -Wall -O3

EXEC = mzf2wav
MAIN = mzf2wav.c
OBJS = physical.o methods.o args.o wav.o

all: $(EXEC)

release: all
	cp $(EXEC) linux/release

.cc.o:
	$(CC) $(CFLAGS) -c $<
	
$(EXEC): $(MAIN) $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm -f *.o core

realclean: clean
	rm -f $(EXEC)
